Repository fortran-lang/minpack, pull requests merged in 2022-02, with the labels that each got.

#33 README: Add a short section about History
  README.md
Labels: documentation

#38 Decision tree with mermaid
  README.md
Labels: documentation

#29 Export minpack API via bind(c)
  fpm.toml
  include/minpack.h
  src/minpack.f90
  src/minpack_capi.f90
  test/api/tester.c
  test/api/testsuite.h
Labels: C-Interface

#41 Fix fpm build in CI
  .github/workflows/CI.yml
  fpm.toml
Labels: CI
