Repository fortran-lang/minpack, pull requests merged in 2022-03, with the labels that each got.

#49 Provide Python bindings for Minpack
  .github/workflows/CI.yml
  config/ci/python-env.yaml
  include/minpack.h
  meson.build
  meson_options.txt
  python/.gitignore
  python/README.rst
  python/ffi-builder.py
  python/meson.build
  python/meson_options.txt
  python/minpack/__init__.py
  python/minpack/exception.py
  python/minpack/library.py
  python/minpack/meson.build
  python/minpack/test_library.py
  python/minpack/typing.py
  python/setup.cfg
  python/setup.py
  src/minpack.f90
  test/api/tester.c
  test/meson.build
Labels: bindings: Python

#55 Enable coverage testing
  .codecov.yaml
  .github/workflows/CI.yml
Labels: CI

#56 Warn if Fortran compiler does not support C-API
  meson.build
Labels: bindings: C

#40 Modernize the tests
  examples/example_lmder1.f90
  examples/example_lmdif1.f90
  src/minpack.f90
  src/minpack_capi.f90
  test/test_chkder.f90
  test/test_hybrd.f90
  test/test_hybrj.f90
  test/test_lmder.f90
  test/test_lmdif.f90
  test/test_lmstr.f90
Labels: refactoring
